# Generated by Django 3.2.13 on 2023-03-22 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0002_settingbranch'),
        ('Quotation', '0007_documentlines_item_uqc'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='SettingBranch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Branch.settingbranch'),
        ),
    ]
