# Generated by Django 3.2.13 on 2023-06-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0008_quotation_settingbranch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='NetTotal',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
