# Generated by Django 3.2.13 on 2023-06-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0009_quotation_nettotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='OrderRequest_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
