from django.urls import path,include
from .views import *

urlpatterns = [
    path('create', create),
    path('all', all),
    path('all_filter', all_filter),
    path('all_filter_page', all_filter_page),
    path('all_filter_assignto', all_filter_assignto),
    path('all_filter_assignto_page', all_filter_assignto_page),
    path('all_filter_reportingto', all_filter_reportingto),
    path('all_filter_reportingto_page', all_filter_reportingto_page),
    path('dashboard', dashboard),
    path('opportunity_bystage', opportunity_bystage),
    path('movingitems', movingitems),
    path('movingitems_count', movingitems_count),
    path('invoice_counter', invoice_counter),
    path('target_create', target_create),
    path('target_all', target_all),
    path('targetqtm_create', targetqtm_create),
    path('targetyr_create', targetyr_create),
    path('targetqty_close', targetqty_close),
    path('targetyr_close', targetyr_close),
    path('targetqtm_all', targetqtm_all),
    path('targetyr_all', targetyr_all),
    path('targetyr_all_filter', targetyr_all_filter),    
    path('analytics', analytics),
    path('top5bp', top5bp),
    path('top5itembyamount', top5itembyamount),
    path('one',one),
    path('login',login),
    path('update', update),
    path('delete', delete),
    path('prod_lead', ProductLead),
    path('proj_lead', ProjectLead),
    path('ase_list', ASE_list),
    path('all_drop_asp', all_drop_asp),
    path("target_visitor_count", target_visitor_count),

]
