# Generated by Django 3.2.13 on 2023-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadId', models.IntegerField(default=0)),
                ('MobileNumber', models.CharField(blank=True, max_length=200)),
                ('CallDuration', models.CharField(blank=True, max_length=200)),
                ('Remarks', models.TextField(blank=True, max_length=200)),
                ('EmployeeId', models.IntegerField(default=0)),
                ('CreateTime', models.CharField(blank=True, max_length=200)),
                ('CreateDate', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
