# Generated by Django 3.2.13 on 2023-02-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='EmployeeName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
