# Generated by Django 3.2.13 on 2023-02-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caller', '0002_caller_employeename'),
    ]

    operations = [
        migrations.AddField(
            model_name='caller',
            name='Brocher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='caller',
            name='Status',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='caller',
            name='StatusType',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
