# Generated by Django 3.2.13 on 2023-03-21 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0003_unitquantitycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='UQC_Code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
