# Generated by Django 3.2.7 on 2022-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('consultant_name', models.CharField(blank=True, max_length=250)),
                ('expected_start_date', models.CharField(blank=True, max_length=50)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('attach', models.CharField(blank=True, max_length=250)),
                ('timestamp', models.CharField(max_length=50)),
            ],
        ),
    ]
