# Generated by Django 3.2.13 on 2022-08-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cardcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
