# Generated by Django 3.2.7 on 2022-08-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_project_cardcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='consultant_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
