# Generated by Django 3.2.13 on 2023-06-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ReceivedAmount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
