# Generated by Django 3.2.13 on 2023-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_auto_20230104_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='doj',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
