# Generated by Django 3.2.13 on 2023-03-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0010_businesspartner_u_landline'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='Adhaar_Number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='PAN_Card',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
