# Generated by Django 3.2.13 on 2023-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0011_auto_20230321_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='Is_Active',
            field=models.CharField(blank=True, default='tYES', max_length=200),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='On_Board_Date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='Password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='Terminate_Date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='Username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
