# Generated by Django 4.2.2 on 2023-09-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0012_auto_20230623_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='AttendedBy',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='ContactTwo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='FunctionDate',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='FunctionType',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='NumberVisits',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='Reference',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='Venue',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='businesspartner',
            name='VisitDate',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
