# Generated by Django 3.2.13 on 2023-09-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0013_businesspartner_attendedby_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='Menu',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
