# Generated by Django 3.2.13 on 2023-02-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='GST',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
