# Generated by Django 4.1.6 on 2023-08-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asp_id', models.CharField(blank=True, max_length=200)),
                ('asp_name', models.CharField(blank=True, max_length=200)),
                ('asp_code', models.CharField(blank=True, max_length=200)),
                ('transport_mode', models.CharField(blank=True, max_length=200)),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('punchin_latitude', models.CharField(blank=True, max_length=200)),
                ('punchin_longitude', models.CharField(blank=True, max_length=200)),
                ('punchout_latitude', models.CharField(blank=True, max_length=200)),
                ('punchout_longitude', models.CharField(blank=True, max_length=200)),
                ('create_date', models.CharField(blank=True, max_length=200)),
                ('create_time', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
