# Generated by Django 4.1.6 on 2023-08-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyservice',
            name='total_distance',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
