# Generated by Django 4.1.6 on 2023-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_dailyservice_total_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ase_id', models.CharField(blank=True, max_length=200)),
                ('checkin_latitude', models.CharField(blank=True, max_length=200)),
                ('checkin_longitude', models.CharField(blank=True, max_length=200)),
                ('checkout_latitude', models.CharField(blank=True, max_length=200)),
                ('checkout_longitude', models.CharField(blank=True, max_length=200)),
                ('distance', models.CharField(blank=True, max_length=200)),
                ('create_date', models.CharField(blank=True, max_length=200)),
                ('create_time', models.CharField(blank=True, max_length=200)),
                ('update_date', models.CharField(blank=True, max_length=200)),
                ('update_time', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='dailyservice',
            name='approval_status',
            field=models.CharField(blank=True, default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='dailyservice',
            name='update_date',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dailyservice',
            name='update_time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
