# Generated by Django 3.2.13 on 2023-08-09 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_dailycustomerservice_dailyservice_approval_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyservice',
            old_name='remark',
            new_name='checkin_remark',
        ),
        migrations.AddField(
            model_name='dailyservice',
            name='checkout_remark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dailyservice',
            name='created_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
