# Generated by Django 3.2.13 on 2023-08-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0004_auto_20230809_0456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycustomerservice',
            old_name='checkin_latitude',
            new_name='DailyService_id',
        ),
        migrations.RenameField(
            model_name='dailycustomerservice',
            old_name='checkin_longitude',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='dailycustomerservice',
            old_name='checkout_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='dailycustomerservice',
            old_name='checkout_longitude',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='dailyservice',
            old_name='checkin_remark',
            new_name='punchin_remark',
        ),
        migrations.RenameField(
            model_name='dailyservice',
            old_name='checkout_remark',
            new_name='punchout_remark',
        ),
    ]
