# Generated by Django 3.2.13 on 2023-08-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_auto_20230809_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycustomerservice',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='dailycustomerservice',
            name='update_time',
        ),
    ]
