# Generated by Django 3.2.13 on 2023-08-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_auto_20230809_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycustomerservice',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
