# Generated by Django 3.2.13 on 2023-08-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0007_dailycustomerservice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycustomerservice',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dailycustomerservice',
            name='source_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
