# Generated by Django 3.2.13 on 2023-08-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0008_auto_20230809_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycustomerservice',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
