# Generated by Django 3.2.13 on 2023-08-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0009_dailycustomerservice_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycustomerservice',
            name='source_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
