# Generated by Django 3.2.13 on 2023-08-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0010_dailycustomerservice_source_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycustomerservice',
            name='source_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
