# Generated by Django 3.2.13 on 2023-08-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0011_dailycustomerservice_source_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyservice',
            name='approval_status',
        ),
    ]
