# Generated by Django 3.2.13 on 2023-08-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0012_remove_dailyservice_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycustomerservice',
            name='remark',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
