# Generated by Django 3.2.13 on 2023-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0013_dailycustomerservice_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyservice',
            name='total_distance',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
    ]
