# Generated by Django 3.2.13 on 2023-08-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0014_alter_dailyservice_total_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailycustomerservice',
            name='lunch_status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
