# Generated by Django 3.2.13 on 2023-01-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('CreatedDate', models.CharField(blank=True, max_length=50)),
                ('CreatedTime', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
