# Generated by Django 3.2.13 on 2023-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0002_expensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='approvalId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='approval_remark',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=200),
        ),
    ]
