# Generated by Django 3.2.13 on 2023-08-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expense', '0004_auto_20230810_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseStatusRemarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_id', models.CharField(blank=True, max_length=5)),
                ('SalesEmployeeCode', models.CharField(blank=True, max_length=5)),
                ('Type', models.CharField(blank=True, max_length=200)),
                ('Status', models.CharField(blank=True, max_length=50)),
                ('Remarks', models.CharField(blank=True, max_length=255)),
                ('Datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
