# Generated by Django 4.2.2 on 2023-06-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryNote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='AwbNo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='DelPart',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
