# Generated by Django 4.2.2 on 2023-06-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryNote', '0002_deliverynote_awbno_deliverynote_delpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='Status',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
