# Generated by Django 4.2.2 on 2023-06-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryNote', '0003_documentlines_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentlines',
            name='Status',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='Status',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
