# Generated by Django 3.2.13 on 2023-06-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryNote', '0005_deliverynote_shippedtype_deliverynote_shippedwith'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='TaxInvoiceDate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='TaxInvoiceNum',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
