# Generated by Django 3.2.13 on 2023-06-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryNote', '0006_auto_20230622_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='Status',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
