# Generated by Django 3.2.13 on 2023-06-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DeliveryNote', '0007_alter_deliverynote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='NetTotal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
