# Generated by Django 3.2.13 on 2022-12-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='remark',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='maps',
            name='shape',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maps',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
