# Generated by Django 3.2.13 on 2023-01-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0002_auto_20221226_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='ContactPerson',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maps',
            name='ResourceId',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maps',
            name='SourceType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
