# Generated by Django 4.1.6 on 2023-08-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TargetVisitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetvisitor',
            name='assigned_to',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='targetvisitor',
            name='created_by',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='targetvisitor',
            name='daily_visit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='targetvisitor',
            name='monthly_target',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
