# Generated by Django 3.2.13 on 2023-08-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TargetVisitor', '0002_alter_targetvisitor_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetvisitor',
            name='visited',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
