# Generated by Django 3.2.13 on 2023-01-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0002_lead_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='productInterest',
            field=models.TextField(blank=True),
        ),
    ]
