# Generated by Django 4.2.2 on 2023-06-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0003_alter_lead_productinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='AssignedDate',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
