# Generated by Django 3.2.13 on 2023-07-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0004_lead_assigneddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='junk_by',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='junk_timestamp',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
