# Generated by Django 4.2.2 on 2023-09-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0005_auto_20230705_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='AttendedBy',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='ContactTwo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='FunctionDate',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='FunctionType',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='lead',
            name='NumberVisits',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='Reference',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='Venue',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='VisitDate',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
