# Generated by Django 3.2.13 on 2023-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0014_order_nettotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentlines',
            name='Item_Code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
