# Generated by Django 3.2.13 on 2023-03-21 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0015_documentlines_item_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentlines',
            old_name='Item_Code',
            new_name='Item_uqc',
        ),
    ]
