# Generated by Django 4.2.2 on 2023-06-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0017_order_settingbranch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderId', models.CharField(blank=True, max_length=5)),
                ('CompanyName', models.CharField(blank=True, max_length=150)),
                ('OrderPlacedOn', models.CharField(blank=True, max_length=30)),
                ('ShipTo', models.CharField(blank=True, max_length=600)),
                ('ExpDel', models.CharField(blank=True, max_length=150)),
                ('DelPart', models.CharField(blank=True, max_length=150)),
                ('AwbNo', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
