# Generated by Django 4.2.2 on 2023-06-16 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0018_deliverycreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryCreate',
        ),
    ]
