# Generated by Django 3.2.13 on 2023-06-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0020_customeraddressextension_customerdocumentlines_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='approval_status',
            field=models.CharField(blank=True, default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='approved_by',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
