# Generated by Django 4.2.2 on 2023-09-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0022_order_attendedby_order_bar_order_bartander_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Fans',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
