# Generated by Django 3.2.13 on 2023-09-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0023_order_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OptionalCustomerName',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
