# Generated by Django 4.2.2 on 2023-09-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0023_order_fans'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='OptionalCustomerName',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
