# Generated by Django 3.2.13 on 2023-09-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0024_order_optionalcustomername'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressextension',
            name='gst_no',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='addressextension',
            name='pan_no',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
